# fly.toml app configuration file generated for courses-dark-sunset-5234 on 2025-06-10T21:16:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'courses-dark-sunset-5234'
primary_region = 'waw'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
